config/routes.rb
Rails.application.routes.draw do
  devise_for :otaku, controllers: { registrations: "registrations" }
    root to: 'home#welcome'
    resources :waifus
    get 'search', to:"home#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/otaku.rb
class Otaku < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/waifu.rb
class Waifu < ApplicationRecord
    has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def welcome
        @waifus = Waifu.all
    end

    def search
        @waifus = Waifu.where('name like ? OR anime like ?',
        "%#{params[:q]}%", "%#{params[:q]}%")
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

end

app/controllers/waifus_controller.rb
class WaifusController < ApplicationController 
    def new 
    end

    def create
        @waifu = Waifu.new(params.require(:waifu).permit(:name, :age, :anime, :description, :main, :avatar))
        @waifu.save
        redirect_to root_path
    end

    def edit
        @waifu = Waifu.find(params[:id])
    end

    def update
        @waifu = Waifu.find(params[:id])
        @waifu.update(params.require(:waifu).permit(:name, :age, :anime, :description, :main, :avatar))
        redirect_to root_path
    end

    def destroy
        @waifu = Waifu.find(params[:id])
        @waifu.delete
        redirect_to root_path
    end

    def show
        @waifu = Waifu.find(params[:id])
    end

    def index
        @waifus = Waifu.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/search.html.erb
<h1>Resultados da busca</h1>
<ul>
  <% @waifus.each do |waifu| %>
    <li><%= link_to waifu.name, waifu_path(waifu.id) %> - <%= waifu.anime %></li>
  <% end %>
</ul>

app/views/home/welcome.html.erb
<div class="container pt-1 pb-3 text-center">
<h1><strong>♥ WAIFU LIST ♥</strong></h1>
<h3><p>Seja Bem-Vindo Mestre!</p></h3>
</div>

<div class="container text-center">
<%= form_with url: search_path, method: :get do %>
    <%= label_tag :q, 'Busca:' %>
    <%= text_field_tag :q %>
    <%= submit_tag 'Encontrar' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<html>
  <head>
    <title>WaifuList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Las Noches TM">
    <meta name="author" content="Rodrigo Las Noches">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    
  </head>

  <body>

    <style class="back">
       body {
              background: url(<%=asset_path 'Cerejera.png' %>);
              background-repeat: no-repeat;
              background-size: cover;
              background-position: center;
              background-attachment: fixed;
              height: 100%
              margin: 0px;
              background-color:#ffc0cb
            }
    </style>

      <header>
      
        <div class="container-xxl pb-1 pt-1" style="background-color: #de3163">
        <ul class="nav justify-content-end">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          
          <% if otaku_signed_in? %>

            <!- <%= current_otaku.email %> ->
            
            <%= link_to 'SETTINGS', edit_otaku_registration_path, :class => "btn btn-light" %> ||
            <%= link_to 'LOGOUT', destroy_otaku_session_path, :class => "btn btn-light",  data: { turbo_method: :delete } %> ||
          <% else %>
            <%= link_to 'REGISTRAR', new_otaku_registration_path, :class => "btn btn-light" %> ||
            <%= link_to 'LOGIN', otaku_session_path, :class => "btn btn-light" %> ||
          <% end %>
        
        <%= link_to 'INICIO', root_path, :class => "btn btn-light" %> ||
        <%= link_to 'ADICIONAR', new_waifu_path, :class => "btn btn-light" %> ||
        <%= link_to 'LISTA DE WAIFUS', waifus_path, :class => "btn btn-light" %>
        </ul>
        </div>
          <style>
            h1 {color:red;}
            p {color:purple;}
        </style>  
        
      </header>

      
    
    <%= yield %>
    
    <div class="container">
    <footer class="fixed-bottom">
      Criado por LasNochesDev
    </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

</html>

app/views/waifus/edit.html.erb
<%= form_for @waifu do |w| %>
    <%= w.label :name, 'NAME:' %><br>
    <%= w.text_field :name %><br>
    <%= w.label :anime, 'ANIME:' %><br>
    <%= w.text_field :anime %><br>
    <%= w.label :description, 'DESCRIÇÃO:' %><br>
    <%= w.text_field :description %><br>
    <%= w.label :main, 'PRINCIPAL:' %>
    <%= w.check_box :main %>
    <%= w.label :avatar %><br>
    <%= w.file_field :avatar %><br>
    <%= w.submit 'EDITAR' %>
<% end %>

app/views/waifus/index.html.erb
<h1><div class="container text-center border border-light rounded ms-6"> ESSA É SUA WAIFU LIST! </div></h1>

<% @waifus.each do |waifu| %>
    <div class="container-sm  pb-1 pt-1 border border-top-0 border-left-0 border-light rounded-3" style="background-color: #d8bfd8">
    <%= image_tag waifu.avatar, style: 'width: 25%' %>
    
    <div><%= waifu.name %></div>
    <div><%= waifu.anime %></div>
    <div><%= waifu.description %></div>

    <%= link_to 'EDITAR', edit_waifu_path(waifu), :class => "btn btn-outline-info" %>
    <%= link_to 'DELETAR', waifu_path(waifu), :class => "btn btn-outline-danger" %>
    </div>
    <br>
<% end %>

app/views/waifus/new.html.erb
<div class="container display-4 text-center border border-danger rounded-pill" style="background-color: #d8bfd8";>
<strong>
Nos Apresente Sua Nova Waifu!
</strong>
</div>

<%= form_for Waifu.new do |w| %>
    <br>
    <%= w.label :name, 'NOME:' %><br>
    <%= w.text_field :name %><br>
    <%= w.label :anime, 'ANIME:' %><br>
    <%= w.text_field :anime %><br>
    <%= w.label :description, 'DESCRIÇÃO:' %><br>
    <%= w.text_field :description %><br>
    <%= w.label :main, 'WAIFU PRINCIPAL:' %>
    <%= w.check_box :main %><br>
    <%= w.label :avatar %><br>
    <%= w.file_field :avatar %><br>
    <%= w.submit 'Criar' %><br>
<% end %>
<br>


app/views/waifus/show.html.erb
<div class="container display-6 pb-3 pt-2 texter-center">
RESULTADOS 
</div>
<div class="container-sm  pb-1 pt-1 border border-top-0 border-left-0 border-light rounded-3" style="background-color: #d8bfd8">
    <div><%= image_tag @waifu.avatar, style: 'width: 25%' %></div>
    <div><%= @waifu.name %></div>
    <div><%= @waifu.age %></div>
    <div><%= @waifu.anime %></div>
    <div><%= @waifu.description %></div>
    
    <%= link_to 'EDITAR', edit_waifu_path(@waifu), :class => "btn btn-outline-info" %>
    <%= link_to 'DELETAR', waifu_path(@waifu), :class => "btn btn-outline-danger" %>
    <br>

</div>